# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manual.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1333, 505)
        Dialog.setStyleSheet("background-color: rgb(6, 53, 95);")
        self.Forward = QtWidgets.QPushButton(Dialog)
        self.Forward.setGeometry(QtCore.QRect(140, 240, 93, 28))
        self.Forward.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"border-radius:10px;\n"
"")
        self.Forward.setObjectName("Forward")
        self.Backward = QtWidgets.QPushButton(Dialog)
        self.Backward.setGeometry(QtCore.QRect(140, 320, 93, 28))
        self.Backward.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"border-radius:10px;\n"
"")
        self.Backward.setObjectName("Backward")
        self.Rigth = QtWidgets.QPushButton(Dialog)
        self.Rigth.setGeometry(QtCore.QRect(260, 280, 93, 28))
        self.Rigth.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"border-radius:10px;\n"
"")
        self.Rigth.setObjectName("Rigth")
        self.Left = QtWidgets.QPushButton(Dialog)
        self.Left.setGeometry(QtCore.QRect(20, 280, 93, 28))
        self.Left.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"border-radius:10px;\n"
"")
        self.Left.setObjectName("Left")
        self.Stop = QtWidgets.QPushButton(Dialog)
        self.Stop.setGeometry(QtCore.QRect(140, 280, 93, 28))
        self.Stop.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"border-radius:10px;\n"
"")
        self.Stop.setObjectName("Stop")
        self.lcdmanual = QtWidgets.QLCDNumber(Dialog)
        self.lcdmanual.setGeometry(QtCore.QRect(10, 90, 221, 101))
        self.lcdmanual.setObjectName("lcdmanual")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 50, 141, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(400, 310, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(690, 20, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(740, 20, 16, 16))
        self.label_4.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 0, 0);\n"
"border-radius:30px;")
        self.label_4.setObjectName("label_4")
        self.Screenshot = QtWidgets.QPushButton(Dialog)
        self.Screenshot.setGeometry(QtCore.QRect(830, 410, 201, 61))
        self.Screenshot.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.Screenshot.setObjectName("Screenshot")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(240, 90, 231, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.SpeedSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.SpeedSlider.setMaximum(255)
        self.SpeedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.SpeedSlider.setObjectName("SpeedSlider")
        self.verticalLayout.addWidget(self.SpeedSlider)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 380, 151, 111))
        self.label_5.setStyleSheet("image: url(:/logo/img.jpg);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.Webcamlabel = QtWidgets.QLabel(Dialog)
        self.Webcamlabel.setGeometry(QtCore.QRect(680, 50, 441, 351))
        self.Webcamlabel.setStyleSheet("")
        self.Webcamlabel.setText("")
        self.Webcamlabel.setObjectName("Webcamlabel")

        self.retranslateUi(Dialog)
        self.SpeedSlider.valueChanged['int'].connect(self.lcdmanual.display) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Forward.setText(_translate("Dialog", "Forward"))
        self.Backward.setText(_translate("Dialog", "Backward"))
        self.Rigth.setText(_translate("Dialog", "Right"))
        self.Left.setText(_translate("Dialog", "Left"))
        self.Stop.setText(_translate("Dialog", "Stop"))
        self.label.setText(_translate("Dialog", "Your Speed "))
        self.lineEdit.setText(_translate("Dialog", "->Not Connected"))
        self.label_3.setText(_translate("Dialog", "Live"))
        self.label_4.setText(_translate("Dialog", "TextLabel"))
        self.Screenshot.setText(_translate("Dialog", "ScreenShot"))
        self.label_2.setText(_translate("Dialog", "Control Your Speed"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
